Added activity feed
xboxapi/Python-Wrapper pull request #2
Opened 2016-09-27 17:22 UTC by oksim14

Added /v2/activity-feed

Very useful :)

2016-09-27 17:23 UTC, oksim14 commented
+ small code review in send_message method

2016-09-28 03:23 UTC, ghost requested changes
Just one minor change, but other than that looks good. Thanks!

2016-09-28 03:23 UTC, voidpirate commented on xboxapi/xbox_api.py
> +        res = requests.post(url, headers=headers, data=data)
Can you do the `json.dumps(data)` here instead of when passing as a parameter?

2016-09-28 09:25 UTC, oksim14 commented
Done, json.dumps() moved to send_post method 👍

2016-09-29 04:06 UTC, merged

2016-09-29 04:06 UTC, voidpirate commented
Thanks! TGTM